### ISSUE TITLE
use correct package manager for package.json

### ISSUE THREAD

**Issue by aspala** [num42/n42-buildscripts#18]
if package.json is present, we want to install npm dependencies.

Currently there exist two major package managers: **yarn** and **npm**. 

We should detect which package manager has been previously used to install dependencies and use it again. Using the other pm may result in failed installations. 

npm5 has a `package-lock.json` lockfile. 
yarn has a lockfile called `yarn.lock`

we should check which lockfile has been generated before or default to yarn ;)

**Comment by Lutzifer** [comment]
@aspala is this still a thing?

**Comment by aspala** [comment]
@Lutzifer yes

I think it is possible to solve it like this:

```
-e package.json =>

      -e package.lock => npm install;

      -e yarn.lock => installYarn(); yarn install;

      !-e package.lock && !-e yarn.lock => installYarn(); yarn install;
 
```

**Comment by Lutzifer** [comment]
@aspala 

two more years later: still a thing?

**Comment by aspala** [comment]
in theory yes, we need to detect which package-manager the project uses and use that for installing the node-dependencies. 

I will submit a PR later which fixes this.
