### ISSUE TITLE
Proposal: add latest ruby version check to bootstrap.sh

### ISSUE THREAD

**Issue by aspala** [num42/n42-buildscripts#5]
many of our projects use ruby and we need to update it regularly, it would be nice if the bootstrap script tells us to do so

what do we need to do:
- [ ] add latest ruby-version to this repo https://raw.githubusercontent.com/num42/n42-ios-bootstrap-shell/master/.ruby-version
- [ ] add a check to the bootstrap script to above url and compare with local repo .ruby-version if any

**Comment by Lutzifer** [comment]
the latest ruby version to use differs across platforms and projects sometimes

**Comment by aspala** [comment]
yes, but it could function as a reminder to check and update ruby-version if needed. hence warning, no error ;)

**Comment by aspala** [comment]
not needed anymore
